# version: 2.1
# jobs:

# build:
#   docker:
#     - image: circleci/node:7.10

#   working_directory: ~/react200-budget-tracker

#   steps:
#     - checkout

#     # Download and cache dependencies
#     - restore_cache:
#         keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#           # fallback to using the latest cache if no exact match is found
#           - v1-dependencies-

#     - run: npm install

#     - save_cache:
#         paths:
#           - node_modules
#         key: v1-dependencies-{{ checksum "package.json" }}

#     # run tests!
#     - run: npm test
# deploy:
#   docker:
#     - image: buildpack-deps:trusty
#   steps:
#     - checkout
#     - run:
#         name: Deploy Master to Heroku
#         command: |
#           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
