version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code arrived
          command: |
            ls -l
      - run:
          name: Its own container
          command: |
            node -v
